### ISSUE TITLE
Switch to VSFilter as subtitle renderer

### ISSUE THREAD

**Issue by nixxquality** [nixxquality/WebMConverter#100]
Branching this off from #96.

assrender is unfortunately out of date by about 2 years, which is a problem since ASS is a rapidly developing format.

The current issue with using VSFilter is that it doesn't have an automatic font loading solution like assrender.

There needs to be some kind of temporary font loading solution on my part.

**Comment by RDF2050** [comment]
You can ask for help at #irrationa-typesetting-wizardry@irc.rizon.net

I am sure there will be someone who can help you out.

**Comment by nixxquality** [comment]
I'm fairly sure I know what I need to do ([AddFontResource](http://msdn.microsoft.com/en-us/library/windows/desktop/dd183326%28v=vs.85%29.aspx)) I just need to get around to writing all the code that makes sure I don't have any stupid memory leaks or something.

**Comment by RDF2050** [comment]
Nonetheless, it can be useful for your current project.

**Comment by Dozodouzo** [comment]
I was just talking with @line0 on this and a few others in #irrational-typesetting-wizardry and he pointed me in this direcion: https://github.com/line0/ExRelease/blob/master/ExRelease.psm1#L666

**Comment by nixxquality** [comment]
To be honest, I'm somewhat surprised.
You don't have to worry about not (un)loading fonts that are already installed on the system?

**Comment by Dozodouzo** [comment]
I think with AddFontResourceEx it is temporary or only for the current session.

**Comment by nixxquality** [comment]
Included in [v2.16.0](https://github.com/nixxquality/WebMConverter/releases/tag/v2.16.0).
