### ISSUE TITLE
Make input and output selections remember folders separately 

### ISSUE THREAD

**Issue by Cerzel** [nixxquality/WebMConverter#101]
You know, like how Firefox will default to the last folder you saved an image to when saving a new image, and default to the last folder you opened an image from when opening one, instead of just using which folder was used last, regardless of whether it's opening or saving, which is what WebMConverter is currently doing.

Don't know how hard this is to do, but as I always want to save the output to my desktop, while taking the input from any number of different folders around my PC, it's a pain to need to navigate from the opposite location each time.

**Comment by nixxquality** [comment]
Included in [v2.15.0](https://github.com/nixxquality/WebMConverter/releases/tag/v2.15.0).

**Comment by Cerzel** [comment]
Damn, that was quick. Cheers.
