### ISSUE TITLE
Dubbing image/video

### ISSUE THREAD

**Issue by randoomdude** [nixxquality/WebMConverter#102]
Would you be able to add an option that let's you to add multiple files so that you can add audio like .mp3 or .ogg to image/video like .gif or .webm to output video using the converter?

**Comment by nixxquality** [comment]
Included in [v2.16.0](https://github.com/nixxquality/WebMConverter/releases/tag/v2.16.0).

**Comment by randoomdude** [comment]
just tried, seems to not work for either .gifs or .jpg, still using basic command to add audio
http://a.pomf.se/sothfk.jpg

**Comment by nixxquality** [comment]
Ah yes, see #104

**Comment by randoomdude** [comment]
works, but video stops after first loop, is there a way to let video continue looping?
http://a.pomf.se/qjxggy.webm

**Comment by nixxquality** [comment]
It will loop now.

**Comment by randoomdude** [comment]
kept it running cause I thought maybe it was in minutes, but it's not stopping (thanks for everything, even up to this point i'm really grateful, even if you do nothing else I appreciate what you've done)
http://a.pomf.se/uuznwa.png

**Comment by nixxquality** [comment]
Welp, that's what I get for assuming AviSynth provided a sane value for FrameCount on audio streams.
I'll see what I can do.

**Comment by nixxquality** [comment]
I've kind of bombarded everyone with a bunch of unnecessary updates, so I'll save this fix for when I'm implementing something else as well.
For now, after you have applied all your processings and you're ready to encode, click Advanced and change
```
Loop(-1).AudioDub(dub).Trim(0,dub.FrameCount)
# to
Loop(-1).AudioDub(dub).Trim(0,int(dub.AudioDuration * last.FrameRate))
```

**Comment by randoomdude** [comment]
welp, more hiccups i'll just wait for your next update, but if it helps
http://a.pomf.se/ipfwli.png

**Comment by nixxquality** [comment]
I forgot that AudioDuration is a 2.60 thing.
This should work (unless your audio is longer than (2^31 samples[[1]](http://avisynth.nl/index.php/Clip_properties))
```
Loop(-1).AudioDub(dub).Trim(0,int(dub.AudioLength / dub.AudioRate * last.FrameRate))
```

**Comment by randoomdude** [comment]
holy shit it works
it bloats 4 minutes songs to like 15mb but it works!

**Comment by nixxquality** [comment]
Yeah, I think there's a bug where it thinks the video is like 0.01 seconds even though it's being looped, so if you use the automatic bitrate it will turn into something insane.

Just set it manually to like 800 KB/s or something for now.

**Comment by randoomdude** [comment]
just realized there isn't an option to let audio continue past video boundries for still images in 2.16.2 like there was in 2.16.1, only the options for trimmed audio and loop

**Comment by nixxquality** [comment]
Looping it is functionally equivalent, the only difference is that you're looping 1 image instead of 15.

**Comment by randoomdude** [comment]
looping makes is making it much larger, sometimes 10mb larger for .jpg

**Comment by randoomdude** [comment]
looping is making it much larger, sometimes 10mb larger for .jpg

**Comment by nixxquality** [comment]
I guess that's true, yeah. I'll add it as a separate mode. If you need to dub a static jpg right now just choose the Trim audio option, go to Advanced mode, and remove the Trim command.
```
Trim(AudioDub(FFAudioSource(""{0}"",cachefile=""{1}"")), 0, last.FrameCount)
#to
AudioDub(FFAudioSource(""{0}"",cachefile=""{1}""))
```

**Comment by nixxquality** [comment]
That should be all the issues with DubFilter taken care of. Included in [v2.16.3](https://github.com/nixxquality/WebMConverter/releases/tag/v2.16.3).

**Comment by randoomdude** [comment]
just re-checked, loop video option still uses
Loop(-1).AudioDub(dub).Trim(0,dub.FrameCount)
instead of 
Loop(-1).AudioDub(dub).Trim(0,int(dub.AudioLength / dub.AudioRate * last.FrameRate))

**Comment by nixxquality** [comment]
Oops.
