### ISSUE TITLE
can't encode anything

### ISSUE THREAD

**Issue by Ryoandr** [nixxquality/WebMConverter#103]
everything I try results in error "not an avisynth 2 c plugin: ffms2.dll"
full log : 

Arguments for pass 1: -f nut -i pipe:0   -an -c:v libvpx -threads 6 -slices 2 -metadata title="Bender nuit d ivresse" -quality best -lag-in-frames 16 -auto-alt-ref 1 -minrate:v 1053K -b:v 1053K -maxrate:v 1053K -bufsize 631K -rc_init_occupancy 4212K -qcomp 1 -fs 3M -pass 1 -passlogfile "C:\Users\Ryo\AppData\Local\Temp\ffmpeg2pass" -f webm -y "NUL"
Arguments for pass 2: -f nut -i pipe:0   -c:v libvpx -threads 6 -slices 2 -metadata title="Bender nuit d ivresse" -quality best -lag-in-frames 16 -auto-alt-ref 1 -minrate:v 1053K -b:v 1053K -maxrate:v 1053K -bufsize 631K -rc_init_occupancy 4212K -qcomp 1 -fs 3M -pass 2 -passlogfile "C:\Users\Ryo\AppData\Local\Temp\ffmpeg2pass" -f webm -y "C:\Ryo\Vids\Bender nuit d ivresse.webm"
--- CREATING AVISYNTH PROXY --- 
[avisynth @ 0035cc60] Not An Avisynth 2 C Plugin: ffms2.dll
(FFMS2.avsi, line 3)
C:\Users\Ryo\AppData\Local\Temp\tmp2E4E.tmp: Unknown error occurred

[nut @ 0000000002ac7840] No main startcode found.
pipe:0: Invalid data found when processing input
--- FFMPEG HAS EXITED ---
--- ENTERING PASS 2 ---
--- CREATING AVISYNTH PROXY --- 
[avisynth @ 0058cc60] Not An Avisynth 2 C Plugin: ffms2.dll
(FFMS2.avsi, line 3)
C:\Users\Ryo\AppData\Local\Temp\tmp2E4E.tmp: Unknown error occurred

[nut @ 0000000000317940] No main startcode found.
pipe:0: Invalid data found when processing input
--- FFMPEG HAS EXITED ---

ffmpeg.exe exited with exit code 1. That's usually bad.
If you have no idea what went wrong, open an issue on GitHub and copy paste the output of this window there.

**Comment by nixxquality** [comment]
Are you using AviSynth outside of WebM for Retards? Seems like it's loading FFMS2.avsi from somewhere, but that's not from my end.

If not, try looking in your Webm for Retards/Binaries/Win32 folder and look for it there.

**Comment by Ryoandr** [comment]
yeah, I use a particular avisynthMTand plugins combination. I absolutely need that specific combination for other encodings. Anyway to prevent the converter from using my avisynth config ?

**Comment by nixxquality** [comment]
I don't think that's possible, no..

Since you seem fluent in AviSynth, you should be able to make a script in AvsPmod and load the .avs file.

I'm afraid there's nothing I can do, though.

**Comment by Ryoandr** [comment]
ok, tried to load an avs and it didn't work, but temporarily renaming my plugin folder worked. This will do I guess.
