### ISSUE TITLE
Problem making webms with wmv files

### ISSUE THREAD

**Issue by tinmanog** [nixxquality/WebMConverter#107]
The webm that's produced seems to just have the first frame from a trim and that's it. 

This shows up in the conversion window

[avisynth @ 00485fe0] FFAudioSource: Seeking is severely broken
C:\Users\Noneofyourbusiness\AppData\Local\Temp\tmpB79F.tmp: Unknown error occurred

and this happened with another wmv file

avisynth @ 01f05fe0] FFAudioSource: Seeking is severely broken
C:\Users\Noneofyourbusiness\AppData\Local\Temp\tmp9944.tmp: Unknown error occurred

Any wmv file I try to convert just has a single frame.

Using the latest version of webmconverter btw

**Comment by nixxquality** [comment]
Could you please try something for me, and see if it works?
Take your input file, add your trims and such and press the Export button.
Now, open the .avs file you saved somewhere with Notepad or something, and change this line:
```
FFVideoSource("...",cachefile="...",track=0)
# to
FFVideoSource("...",cachefile="...",track=0,seekmode=0)
```
Save your changes and open the .avs file with WebM for Retards, and see if encoding works.
Please report back with your findings.

**Comment by tinmanog** [comment]
[nut @ 00000000003194a0] No main startcode found.
pipe:0: Invalid data found when processing input

also the avs file is like 1kb

**Comment by nixxquality** [comment]
Yeah, avs files are supposed to be tiny. Is that all the errors you get in your log?
There should be something before that like
```
--- CREATING AVISYNTH PROXY --- 
[avisynth @ 00758440] Script error: there is no function named "txtsub"
(.avs, line 7)
.avs: Unknown error occurred
```

I don't mind if you take out the filename.

**Comment by tinmanog** [comment]
avisynth @ 021c66a0] Script error: FFAudioSource does not have a named argument "seekmode"
nope.avs, line 4)
[nut @ 0000000002ac96a0] No main startcode found.
nope.avs: Unknown error occurred
--- FFMPEG HAS EXITED ---
pipe:0: Invalid data found when processing input

**Comment by nixxquality** [comment]
You put the seekmode argument on the wrong command.
```
AudioDub(FFVideoSource("...",cachefile="...",track=0), FFAudioSource("...",cachefile="...",track=1))
# to
AudioDub(FFVideoSource("...",cachefile="...",track=0, seekmode=0), FFAudioSource("...",cachefile="...",track=1))
```
See if that works.

**Comment by tinmanog** [comment]
instead of track=0 it says something along the lines of ffindex",track=1)

Should I do seekmode=1? or should I change the track to track=0 and then do seekmode=0?

**Comment by nixxquality** [comment]
No, leave the track argument as it is, and add seekmode=0.
In your case it would be `track=1, seekmode=0`.

**Comment by tinmanog** [comment]
[avisynth @ 021d66a0] FFAudioSource: Seeking is severely broken
avs: Unknown error occurred

**Comment by nixxquality** [comment]
That's too bad, I don't know if there's anything I can do for you.
Try reporting it on the [FFMS2 issue tracker](https://github.com/FFMS/ffms2/issues/new).

Make sure to include details on the codecs; for example, if you are using MPC, do this:
![how to get mediainfo](https://a.pomf.se/hjwjjw.png)
Then paste all that text into your issue report.

**Comment by tinmanog** [comment]
I'm not exactly sure how to phrase this report. Do I just copy paste mediainfo on the  repost and just say I'm having problems making webms with it?

also if it wouldn't be too much trouble can you look into this? 
https://github.com/nixxquality/WebMConverter/issues/61

**Comment by nixxquality** [comment]
Just say something like FFAudioSource fails to load codec ______; "Seeking is severely broken."

Then put the MediaInfo in the issue description.

You should also include a link back to this issue by writing nixxquality/WebMConverter#107

**Comment by tinmanog** [comment]
Is that the same with ogm files?

**Comment by nixxquality** [comment]
Have you tried opening the file with the dll qyot27 uploaded?
> http://www.mediafire.com/?pe3g37b73j4kjdq

If you take that dll and replace `Binaries/Win32/ffms2.dll` you should be able to test if the new asf decoder is up to scratch.

**Comment by tinmanog** [comment]
I tried replacing some of the files like ffms2.dll but that just seems to have made the converter stop working

**Comment by nixxquality** [comment]
Are you on the latest version of WebM for Retards? The converter should work fine even with that dll he linked.
