### ISSUE TITLE
Large subtitle files will crash upon conversion

### ISSUE THREAD

**Issue by Dozodouzo** [nixxquality/WebMConverter#108]
So I was testing things since the move to VSFilter and i don't know if this is an issue with VSFilter, avisynth, ffmpeg, or your program itself but if you try to hardsub something with an extremely large .ass subtitle file (i.e. this: http://www.nyaa.se/?page=view&tid=492904 in this particular case the subtitles them self is 86MB) it crashes and does not complete the encode. below is the log of the Conversion Progress window.

http://privatepaste.com/dbedbd4368

**Comment by nixxquality** [comment]
I tried using a slightly different encoding setup (avs2yuv | ffmpeg) but even then the results are pretty sketchy.
https://a.pomf.se/bdcaxv.webm

I'm using the same VSFilter dll that's included with MPC (and it plays in that), so I'm pretty stumped.

**Comment by Dozodouzo** [comment]
yeah I blame Hdr for making a 10,000 line gradient frame by frame typeset.

**Comment by nixxquality** [comment]
Actually, now that I mess around in MPC more, it seems like a bug in their VSFilter. It seems every other frame takes 15 seconds to render.
If you're using the default VSFilter, try skipping (Ctrl+G) to frame 2047 for example.

If you don't mind losing the ability to hardsub DVD subtitles (Vobsub), you can replace the VSFilter.dll in your `WebM for Retards/Binaries/Win32 folder` with [xy-VSFilter's](https://github.com/Cyberbeing/xy-VSFilter/releases/download/3.0.0.306/xy-VSFilter_3.0.0.306_x86.zip).
That one seems to render it flawlessly.

You might want to report this bug with the MPC developers.

**Comment by Dozodouzo** [comment]
oh i was under the impression that you had used xy-VSFilter in the first place as that has much more compatibility with the typesetting done in today's fansubs.

**Comment by nixxquality** [comment]
I was under the mistaken impression that xy-VSFilter didn't support rendering VobSub (god knows why) so that's why I chose MPC's VSFilter.

I will go ahead and replace it now, though.

**Comment by nixxquality** [comment]
Turns out my mistaken impression wasn't so mistaken after all.
I can't get VobSub to work when using xy-VSFilter.

I don't want to disable a feature to make another one work, nor do I want to include two dlls because the Binaries folder is already a bit big.

I'll let anyone who needs this level of typesetting swap out to the xy-VSFilter dll if they need it, but I'm not going to change the default.
