### ISSUE TITLE
Cannot disable audio in Advanced mode

### ISSUE THREAD

**Issue by Mazuo** [nixxquality/WebMConverter#109]
I was making a couple of Webms with audio.
Ever since then I am unable to disable audio.

I have tried checking/unchecking "audio" box, restarting windows, deleting the program and copying the files again.  But none of those ideas worked.

There are no arguments to add audio.
However whenever I create a webm now there is always sound.

Really has me scratching my head.

**Comment by nixxquality** [comment]
Yeah, I recently introduced a bug where audio will audio be encoded if you're in advanced mode. My bad.

Until I've fixed it, you can add "-an" to the end of the arguments list in the Advanced tab.

**Comment by nixxquality** [comment]
For reference, the commit that introduced this bug was 52d5f5e03edbc2b262d9573009fd6fbaf6a6f0ee.

**Comment by nixxquality** [comment]
Included in [v2.16.3](https://github.com/nixxquality/WebMConverter/releases/tag/v2.16.3).
