### ISSUE TITLE
Converted video show a white screen.

### ISSUE THREAD

**Issue by HNKMaster** [nixxquality/WebMConverter#110]
I recorded some footage with FRAPS, and converted it with the WebMConverter, but everytime my video looks like this:

![screwed coding](https://cloud.githubusercontent.com/assets/10904372/6095207/81724094-af2e-11e4-840b-893e0757df7d.png)

Is weird, because I converted successfully videos before without errors, and suddenly I get this. Is a bug, or I made some mistake?

**Comment by nixxquality** [comment]
> @TKGP posted:
Pretty much what it says on the tin. Output is mostly solid white with flickering artifacts and occasional intact frames. Tried with default settings. Sample file: http://www.mediafire.com/download/lhj87t2hntjdgnc/Dwm+2015-02-10+14-13-30-14.7z

**Comment by nixxquality** [comment]
The problem seems to be the layer of alpha (transparency) in the video.

Add ` -pix_fmt yuv420p` to the arguments list in the Advanced tab and see if that fixes it.

**Comment by HNKMaster** [comment]
That's great! Put that command and worked!

Thanks a lot!
