### ISSUE TITLE
FRAPS "Monitor Aero desktop (DWM)" recordings render extremely glitchily.

### ISSUE THREAD

**Issue by TKGP** [nixxquality/WebMConverter#111]
Pretty much what it says on the tin. Output is mostly solid white with flickering artifacts and occasional intact frames. Tried with default settings. Sample file: http://www.mediafire.com/download/lhj87t2hntjdgnc/Dwm+2015-02-10+14-13-30-14.7z

**Comment by nixxquality** [comment]
Duplicate of #110, but thanks for the sample video.
