### ISSUE TITLE
Reset to defaults when loading a new file

### ISSUE THREAD

**Issue by randoomdude** [nixxquality/WebMConverter#113]
would you be able to make it so that you have the option to clear file info from all the fields after video conversion? keeping the file in is useful if I want to keep adjusting the file afterword but if you want to make a new file you have to clear everything yourself each time or just end up opening a new instance of webmconverter

**Comment by nixxquality** [comment]
Yeah. It already resets the filters when you load a new file, so I guess it's not consistent that the rest of the settings aren't.

**Comment by randoomdude** [comment]
I meant more after the conversion is finished, to add a third option to play result and cancel, to clear fields, only clearing fields when loading a new file is assuming you have a new file to load when you just want to clear fields to say, delete the file when its not being used by webmconverter

**Comment by nixxquality** [comment]
You could just load the same file again. I don't think I want to add another button to the conversion dialog.

**Comment by randoomdude** [comment]
okay, thanks
