### ISSUE TITLE
Always Check Audio (Default Preferences?)

### ISSUE THREAD

**Issue by Kyokou** [nixxquality/WebMConverter#114]
Having to check that box every time is one of those mild annoyances I think could be fixed with a config file. Or if I've missed how to do this, let me know I'm an idiot.

**Comment by nixxquality** [comment]
Included in [v2.16.6](https://github.com/nixxquality/WebMConverter/releases/tag/v2.16.6).

**Comment by Kyokou** [comment]
Loves you.
