### ISSUE TITLE
Can't convert with SubRip subtitles

### ISSUE THREAD

**Issue by tinmanog** [nixxquality/WebMConverter#122]
http://kickass.to/vikings-s03e02-the-wanderer-720p-web-dl-dd5-1-h-264-bs-rarbg-t10279424.html
File I used

What came out when trying to convert part of it with subtitles 

Arguments: -f nut -i pipe:0   -c:v libvpx -pix_fmt yuv420p -threads 4 -slices 2 -metadata title="Vikings.S03E02.The.Wanderer.720p.WEB-DL.DD5.1.H.264-BS" -ac 2 -c:a libvorbis -minrate:v 900K -b:v 900K -maxrate:v 900K -bufsize 540K -rc_init_occupancy 3600K -qcomp 1 -b:a 64K -f webm -y "none of your beeswax.webm"
--- CREATING AVISYNTH PROXY --- 
[nut @ 0000000002aaf680] No main startcode found.
pipe:0: Invalid data found when processing input
[avisynth @ 021d6000] TextSub: Can't open "C:\Users\nuhuh\AppData\Local\Temp\50-58-08-58-3E-BD-76-12-F0-26-32-C2-F3-80-30-C9.attachments\sub2.ass"
--- FFMPEG HAS EXITED ---
(C:\Users\nuh uh\AppData\Local\Temp\tmp9BF6.tmp, line 7)
C:\Users\nuh uh\AppData\Local\Temp\tmp9BF6.tmp: Unknown error occurred

ffmpeg.exe exited with exit code 1. That's usually bad.

I could still make the webm if I didn't enable the CC subtitles

**Comment by tinmanog** [comment]
Whoops jumped the gun on that

thanks

**Comment by nixxquality** [comment]
Included in [v2.17.1](https://github.com/nixxquality/WebMConverter/releases/tag/v2.17.1).

Sorry about the delay, turns out the first solution didn't solve shit.
