### ISSUE TITLE
"no audio track" alert on GIFs

### ISSUE THREAD

**Issue by marktaiwan** [nixxquality/WebMConverter#125]
Is the "no audio tracks were found" alert really necessary?

I frequently need to do gif conversions and found the pop up really annoying. Please consider removing it or at least not displaying it for gif files.

![image](https://cloud.githubusercontent.com/assets/7380439/6578137/4a6f9260-c77d-11e4-8d1c-3d341134d2c7.png)

**Comment by nixxquality** [comment]
Sure, sounds reasonable.
