### ISSUE TITLE
Using the "size limit" feature makes the WebM bigger than necessary

### ISSUE THREAD

**Issue by TomHorst** [nixxquality/WebMConverter#128]
Example: Original video has a bitrate of ~1000kbps. 

Using the size limit feature should "adjust the quality to attempt to stay below the limit", right? So when I activate this feature and put the size limit at, let's say, 4MB, the converter should try and stay below 4MB.

But this is not what happens. Rather than staying below 4MB, it seem to try to always REACH 4MB by blowing up the bitrate. The converted file now has a bitrate of ~5000kbps and it's exactly 4MB, even though it's only a few seconds long and shouldn't be that big. 

I didn't have this issue with the old converter by WebMBro. With his version, the converted file is only 700kb.

**Comment by nixxquality** [comment]
That's intentional. You can specify a bitrate manually if you don't want your video blown up.
