### ISSUE TITLE
when using target filesize, some frames at end get cut

### ISSUE THREAD

**Issue by Ryoandr** [nixxquality/WebMConverter#134]
happens in either 1 pass or 2 pass, which defeats using 2 pass mode for optimal usage of filesize. Should always encode all frames in 2 pass, even if filesize overshoots, that can be tweaked either internally or by user tries.

**Comment by nixxquality** [comment]
See #124.

I totally agree that 2 pass becomes useless, but there's nothing I can do about VP8 being shit. I prefer having the -fs argument, after all, that's why the field is called "size **limit**".

Feel free to remove the -fs argument manually in the Advanced tab if you want.
