### ISSUE TITLE
ffmpeg crashing at a certain point when subs are enabled

### ISSUE THREAD

**Issue by shamoke** [nixxquality/WebMConverter#93]
Trying to make a webm of episode 9 from http://bakabt.me/142483-kanokon-dvd-dyn-dvd.html In case the exact time matters it's from 19:56 to 21:00. It doesn't crash if I don't add the subs, though they appear to just be ASS according to mpchc. The converter just stops the file early as though it finished without a problem once ffmpeg crashes.

Crash details below.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ffmpeg.exe
  Application Version:	0.0.0.0
  Application Timestamp:	0004d9f8
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.18229
  Fault Module Timestamp:	51fb1072
  Exception Code:	c0000005
  Exception Offset:	0002e3be
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by nixxquality** [comment]
Not using assrender anymore; Tested with VSFilter and works now.

Should have closed this issue a while ago..
